# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: roderio.YouputDesk
PackageVersion: 0.1.2
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: b9f0f9f4-64f1-581b-a430-6f9885a3f266
ReleaseDate: 2026-10-02
AppsAndFeaturesEntries:
- DisplayName: YouputDesk
  Publisher: roderio
  ProductCode: b9f0f9f4-64f1-581b-a430-6f9885a3f266
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/roderio/youputdesk/releases/download/v0.1.2/YouputDesk-Setup-0.1.2.exe
  InstallerSha256: 1150817F6D4F3B19F91A36B6BC7714B1F2116701F8A79905CD801B850BE5EFF6
- Architecture: arm64
  InstallerUrl: https://github.com/roderio/youputdesk/releases/download/v0.1.2/YouputDesk-Setup-0.1.2.exe
  InstallerSha256: 1150817F6D4F3B19F91A36B6BC7714B1F2116701F8A79905CD801B850BE5EFF6
ManifestType: installer
ManifestVersion: 1.10.0
